package com.example.exchangeratestracking.domain.mapper

import com.example.exchangeratestracking.data.remote.response.CurrentRateResponse
import com.example.exchangeratestracking.presentation.entity.ExchangeRate
import javax.inject.Inject

class CurrentRateResponseToMapExchangeRateMapper @Inject constructor() : (CurrentRateResponse) -> List<ExchangeRate> {

    override fun invoke(currentRateResponse: CurrentRateResponse): List<ExchangeRate> {

        return listOf(
//            ExchangeRate("AED", currentRateResponse.rates.AED),
//            ExchangeRate("AFN", currentRateResponse.rates.AFN),
//            ExchangeRate("ALL", currentRateResponse.rates.ALL),
            ExchangeRate("AMD", currentRateResponse.rates.AMD),
//            ExchangeRate("ANG", currentRateResponse.rates.ANG),
//            ExchangeRate("AOA", currentRateResponse.rates.AOA),
//            ExchangeRate("ARS", currentRateResponse.rates.ARS),
            ExchangeRate("AUD", currentRateResponse.rates.AUD),
//            ExchangeRate("AWG", currentRateResponse.rates.AWG),
            ExchangeRate("AZN", currentRateResponse.rates.AZN),
//            ExchangeRate("BAM", currentRateResponse.rates.BAM),
//            ExchangeRate("BBD", currentRateResponse.rates.BBD),
//            ExchangeRate("BDT", currentRateResponse.rates.BDT),
            ExchangeRate("BGN", currentRateResponse.rates.BGN),
//            ExchangeRate("BHD", currentRateResponse.rates.BHD),
//            ExchangeRate("BIF", currentRateResponse.rates.BIF),
//            ExchangeRate("BMD", currentRateResponse.rates.BMD),
//            ExchangeRate("BND", currentRateResponse.rates.BND),
//            ExchangeRate("BOB", currentRateResponse.rates.BOB),
            ExchangeRate("BRL", currentRateResponse.rates.BRL),
//            ExchangeRate("BSD", currentRateResponse.rates.BSD),
//            ExchangeRate("BTC", currentRateResponse.rates.BTC),
//            ExchangeRate("BTN", currentRateResponse.rates.BTN),
//            ExchangeRate("BWP", currentRateResponse.rates.BWP),
            ExchangeRate("BYN", currentRateResponse.rates.BYN),
//            ExchangeRate("BZD", currentRateResponse.rates.BZD),
            ExchangeRate("CAD", currentRateResponse.rates.CAD),
//            ExchangeRate("CDF", currentRateResponse.rates.CDF),
            ExchangeRate("CHF", currentRateResponse.rates.CHF),
//            ExchangeRate("CLF", currentRateResponse.rates.CLF),
//            ExchangeRate("CLP", currentRateResponse.rates.CLP),
//            ExchangeRate("CNH", currentRateResponse.rates.CNH),
            ExchangeRate("CNY", currentRateResponse.rates.CNY),
//            ExchangeRate("COP", currentRateResponse.rates.COP),
//            ExchangeRate("CRC", currentRateResponse.rates.CRC),
//            ExchangeRate("CUC", currentRateResponse.rates.CUC),
//            ExchangeRate("CUP", currentRateResponse.rates.CUP),
//            ExchangeRate("CVE", currentRateResponse.rates.CVE),
            ExchangeRate("CZK", currentRateResponse.rates.CZK),
//            ExchangeRate("DJF", currentRateResponse.rates.DJF),
            ExchangeRate("DKK", currentRateResponse.rates.DKK),
//            ExchangeRate("DOP", currentRateResponse.rates.DOP),
//            ExchangeRate("DZD", currentRateResponse.rates.DZD),
//            ExchangeRate("EGP", currentRateResponse.rates.EGP),
//            ExchangeRate("ERN", currentRateResponse.rates.ERN),
//            ExchangeRate("ETB", currentRateResponse.rates.ETB),
            ExchangeRate("EUR", currentRateResponse.rates.EUR),
//            ExchangeRate("FJD", currentRateResponse.rates.FJD),
//            ExchangeRate("FKP", currentRateResponse.rates.FKP),
            ExchangeRate("GBP", currentRateResponse.rates.GBP),
//            ExchangeRate("GEL", currentRateResponse.rates.GEL),
//            ExchangeRate("GGP", currentRateResponse.rates.GGP),
//            ExchangeRate("GHS", currentRateResponse.rates.GHS),
//            ExchangeRate("GIP", currentRateResponse.rates.GIP),
//            ExchangeRate("GMD", currentRateResponse.rates.GMD),
//            ExchangeRate("GNF", currentRateResponse.rates.GNF),
//            ExchangeRate("GTQ", currentRateResponse.rates.GTQ),
//            ExchangeRate("GYD", currentRateResponse.rates.GYD),
            ExchangeRate("HKD", currentRateResponse.rates.HKD),
//            ExchangeRate("HNL", currentRateResponse.rates.HNL),
//            ExchangeRate("HRK", currentRateResponse.rates.HRK),
//            ExchangeRate("HTG", currentRateResponse.rates.HTG),
            ExchangeRate("HUF", currentRateResponse.rates.HUF),
//            ExchangeRate("IDR", currentRateResponse.rates.IDR),
//            ExchangeRate("ILS", currentRateResponse.rates.ILS),
//            ExchangeRate("IMP", currentRateResponse.rates.IMP),
            ExchangeRate("INR", currentRateResponse.rates.INR),
//            ExchangeRate("IQD", currentRateResponse.rates.IQD),
//            ExchangeRate("IRR", currentRateResponse.rates.IRR),
//            ExchangeRate("ISK", currentRateResponse.rates.ISK),
//            ExchangeRate("JEP", currentRateResponse.rates.JEP),
//            ExchangeRate("JMD", currentRateResponse.rates.JMD),
//            ExchangeRate("JOD", currentRateResponse.rates.JOD),
            ExchangeRate("JPY", currentRateResponse.rates.JPY),
//            ExchangeRate("KES", currentRateResponse.rates.KES),
            ExchangeRate("KGS", currentRateResponse.rates.KGS),
//            ExchangeRate("KHR", currentRateResponse.rates.KHR),
//            ExchangeRate("KMF", currentRateResponse.rates.KMF),
//            ExchangeRate("KPW", currentRateResponse.rates.KPW),
            ExchangeRate("KRW", currentRateResponse.rates.KRW),
//            ExchangeRate("KWD", currentRateResponse.rates.KWD),
//            ExchangeRate("KYD", currentRateResponse.rates.KYD),
            ExchangeRate("KZT", currentRateResponse.rates.KZT),
//            ExchangeRate("LAK", currentRateResponse.rates.LAK),
//            ExchangeRate("LBP", currentRateResponse.rates.LBP),
//            ExchangeRate("LKR", currentRateResponse.rates.LKR),
//            ExchangeRate("LRD", currentRateResponse.rates.LRD),
//            ExchangeRate("LSL", currentRateResponse.rates.LSL),
//            ExchangeRate("LYD", currentRateResponse.rates.LYD),
//            ExchangeRate("MAD", currentRateResponse.rates.MAD),
            ExchangeRate("MDL", currentRateResponse.rates.MDL),
//            ExchangeRate("MGA", currentRateResponse.rates.MGA),
//            ExchangeRate("MKD", currentRateResponse.rates.MKD),
//            ExchangeRate("MMK", currentRateResponse.rates.MMK),
//            ExchangeRate("MNT", currentRateResponse.rates.MNT),
//            ExchangeRate("MOP", currentRateResponse.rates.MOP),
//            ExchangeRate("MRU", currentRateResponse.rates.MRU),
//            ExchangeRate("MUR", currentRateResponse.rates.MUR),
//            ExchangeRate("MVR", currentRateResponse.rates.MVR),
//            ExchangeRate("MWK", currentRateResponse.rates.MWK),
//            ExchangeRate("MXN", currentRateResponse.rates.MXN),
//            ExchangeRate("MYR", currentRateResponse.rates.MYR),
//            ExchangeRate("MZN", currentRateResponse.rates.MZN),
//            ExchangeRate("NAD", currentRateResponse.rates.NAD),
//            ExchangeRate("NGN", currentRateResponse.rates.NGN),
//            ExchangeRate("NIO", currentRateResponse.rates.NIO),
            ExchangeRate("NOK", currentRateResponse.rates.NOK),
//            ExchangeRate("NPR", currentRateResponse.rates.NPR),
//            ExchangeRate("NZD", currentRateResponse.rates.NZD),
//            ExchangeRate("OMR", currentRateResponse.rates.OMR),
//            ExchangeRate("PAB", currentRateResponse.rates.PAB),
//            ExchangeRate("PEN", currentRateResponse.rates.PEN),
//            ExchangeRate("PGK", currentRateResponse.rates.PGK),
//            ExchangeRate("PHP", currentRateResponse.rates.PHP),
//            ExchangeRate("PKR", currentRateResponse.rates.PKR),
            ExchangeRate("PLN", currentRateResponse.rates.PLN),
//            ExchangeRate("PYG", currentRateResponse.rates.PYG),
//            ExchangeRate("QAR", currentRateResponse.rates.QAR),
            ExchangeRate("RON", currentRateResponse.rates.RON),
//            ExchangeRate("RSD", currentRateResponse.rates.RSD),
            ExchangeRate("RUB", currentRateResponse.rates.RUB),
//            ExchangeRate("RWF", currentRateResponse.rates.RWF),
//            ExchangeRate("SAR", currentRateResponse.rates.SAR),
//            ExchangeRate("SBD", currentRateResponse.rates.SBD),
//            ExchangeRate("SCR", currentRateResponse.rates.SCR),
//            ExchangeRate("SDG", currentRateResponse.rates.SDG),
            ExchangeRate("SEK", currentRateResponse.rates.SEK),
            ExchangeRate("SGD", currentRateResponse.rates.SGD),
//            ExchangeRate("SHP", currentRateResponse.rates.SHP),
//            ExchangeRate("SLL", currentRateResponse.rates.SLL),
//            ExchangeRate("SOS", currentRateResponse.rates.SOS),
//            ExchangeRate("SRD", currentRateResponse.rates.SRD),
//            ExchangeRate("SSP", currentRateResponse.rates.SSP),
//            ExchangeRate("STD", currentRateResponse.rates.STD),
//            ExchangeRate("STN", currentRateResponse.rates.STN),
//            ExchangeRate("SVC", currentRateResponse.rates.SVC),
//            ExchangeRate("SYP", currentRateResponse.rates.SYP),
//            ExchangeRate("SZL", currentRateResponse.rates.SZL),
//            ExchangeRate("THB", currentRateResponse.rates.THB),
            ExchangeRate("TJS", currentRateResponse.rates.TJS),
            ExchangeRate("TMT", currentRateResponse.rates.TMT),
//            ExchangeRate("TND", currentRateResponse.rates.TND),
//            ExchangeRate("TOP", currentRateResponse.rates.TOP),
            ExchangeRate("TRY", currentRateResponse.rates.TRY),
//            ExchangeRate("TTD", currentRateResponse.rates.TTD),
//            ExchangeRate("TWD", currentRateResponse.rates.TWD),
//            ExchangeRate("TZS", currentRateResponse.rates.TZS),
            ExchangeRate("UAH", currentRateResponse.rates.UAH),
//            ExchangeRate("UGX", currentRateResponse.rates.UGX),
            ExchangeRate("USD", currentRateResponse.rates.USD),
//            ExchangeRate("UYU", currentRateResponse.rates.UYU),
            ExchangeRate("UZS", currentRateResponse.rates.UZS),
//            ExchangeRate("VES", currentRateResponse.rates.VES),
//            ExchangeRate("VND", currentRateResponse.rates.VND),
//            ExchangeRate("VUV", currentRateResponse.rates.VUV),
//            ExchangeRate("WST", currentRateResponse.rates.WST),
//            ExchangeRate("XAF", currentRateResponse.rates.XAF),
//            ExchangeRate("XAG", currentRateResponse.rates.XAG),
//            ExchangeRate("XAU", currentRateResponse.rates.XAU),
//            ExchangeRate("XCD", currentRateResponse.rates.XCD),
            ExchangeRate("XDR", currentRateResponse.rates.XDR),
//            ExchangeRate("XOF", currentRateResponse.rates.XOF),
//            ExchangeRate("XPD", currentRateResponse.rates.XPD),
//            ExchangeRate("XPF", currentRateResponse.rates.XPF),
//            ExchangeRate("XPT", currentRateResponse.rates.XPT),
//            ExchangeRate("YER", currentRateResponse.rates.YER),
            ExchangeRate("ZAR", currentRateResponse.rates.ZAR),
//            ExchangeRate("ZMW", currentRateResponse.rates.ZMW),
            ExchangeRate("ZWL", currentRateResponse.rates.ZWL)
        )
    }
}